### ISSUE TITLE
quotes in commands.txt and commands.txt seem to get ignored

### ISSUE THREAD

**Issue by jalbstmeijer** [maartenq/pcrunner#82]
in command.txt:

SERVICE|log /var/log/maillog|/usr/lib64/nagios/plugins/check_log|-F /var/log/maillog -O /dev/null -q "Relay access denied"

in commands.yml:

- name: 'log /var/log/maillog'
  command: '/usr/lib64/nagios/plugins/check_log -F /var/log/maillog -O /dev/null -q "Relay access denied"'
  result_type: 'PROCESS_SERVICE_CHECK_RESULT'

On commands line:

# /usr/lib64/nagios/plugins/check_log -F /var/log/maillog -O /dev/null -q "Relay access denied"; echo $?
Log check ok - 0 pattern matches found|match=0;;;0
0

Processed by pcrunner:

Nov 06 10:49:05 pcrunner.main [634] DEBUG    check log /var/log/maillog: on run queue
Nov 06 10:49:05 pcrunner.main [634] DEBUG    check log /var/log/maillog: started at 1509961745.71
Nov 06 10:49:05 pcrunner.main [634] DEBUG    check log /var/log/maillog: excecuting /usr/lib64/nagios/plugins/check_log -F /var/log/maillog -O /dev/null -q "Relay access denied"
Nov 06 10:49:05 pcrunner.main [634] DEBUG    check log /var/log/maillog: started with PID: 1028
Nov 06 10:49:05 pcrunner.main [634] DEBUG    check log /var/log/maillog: finished: PID: 1028  return code 3

The result is:

an exit code 3 and string: Unknown argument: access

So I assume, the quotes are lost during pcrunner processing.

**Comment by jalbstmeijer** [comment]
i can confirm it works in v0.3.7

**Comment by jalbstmeijer** [comment]
Sorry, seems i did not test correctly.

So the patch seems to have fixed the  "exit code 3 and string: Unknown argument: access" result.

But it actually still is not processing the quotes correctly.

I noticed it is still not alerting, when  /var/log/maillog  contains "Relay access denied" 
 - name: 'log /var/log/maillog'
  command: '/usr/lib64/nagios/plugins/check_log -F /var/log/maillog -O /dev/null -q "Relay access denied"'
  result_type: 'PROCESS_SERVICE_CHECK_RESULT'

Simplifying the test, still not alerting when  /var/log/maillog contains "denied"

 - name: 'log /var/log/maillog'
  command: '/usr/lib64/nagios/plugins/check_log -F /var/log/maillog -O /dev/null -q "denied"'
  result_type: 'PROCESS_SERVICE_CHECK_RESULT'

Removing the quotes and it works again;

 - name: 'log /var/log/maillog'
  command: '/usr/lib64/nagios/plugins/check_log -F /var/log/maillog -O /dev/null -q denied'
  result_type: 'PROCESS_SERVICE_CHECK_RESULT'

And the problem remains the debug log is showing the exact correct command to execute and for som reason it is not what is executed.

Jan 16 10:28:51 pcrunner.main [21035] DEBUG    check log /var/log/maillog: excecuting /usr/lib64/nagios/plugins/check_log -F /var/log/maillog -O /dev/null -q "Relay access denied"

**Comment by maartenq** [comment]
v0.3.8 should fix #82

**Comment by maartenq** [comment]
fixed
