### ISSUE TITLE
systemd Unit Files for Centos7/Redhat7 rpm

### ISSUE THREAD

**Issue by jalbstmeijer** [maartenq/pcrunner#93]
Currently the rpm supplies /etc/init.d files.
For Centos7/Redhat7 it is preferred to use systemd Unit Files.

**Comment by maartenq** [comment]
Added  pcrunner/systemd/pcrunner.service  and a new spec file which should make a RPM with systemd unit files activated when build on rhel7 in devel branch. But not tested yet. see: 13d6845

**Comment by jalbstmeijer** [comment]
Tested on Centos7 and seems to work.
Only thing that complaints is;

pcrunner.service: Supervising process xxxxx which is not our child. We'll most likely not notice when it exits

This message goes away when commenting the following in /usr/lib/systemd/system/pcrunner.service

Type=forking

Any idea why you thought this option was needed?

**Comment by jalbstmeijer** [comment]
Correction , after commenting 'Type=forking' .. the  Supervising warning is still showed but not consistently.

Commenting 'Type=forking' and using 'ExecStart=/usr/bin/pcrunner -a start' to start pcrunner in the foreground seems to solve the  Supervising warning.

**Comment by maartenq** [comment]
yeah, guess that was the idea (no daemon/forking) systemd should do that. Don't know why the type forking still got in. Fixed it in 8e6ad6e. Can you test it?

**Comment by jalbstmeijer** [comment]
el6 rpm build fails;

/usr/bin/install: cannot create regular file `/root/rpmbuild/BUILDROOT/pcrunner-0.3.9-1.x86_64/etc/rc.d/init.d/pcrunner': No such file or directory
error: Bad exit status from /var/tmp/rpm-tmp.BJxaf0 (%install)


fix:

--- pcrunner-0.3.9.org/pcrunner.spec	2018-07-16 06:25:53.858207572 -0400
+++ pcrunner-0.3.9/pcrunner.spec	2018-07-16 06:23:35.080854968 -0400
@@ -84,6 +84,7 @@
     %{buildroot}%{_unitdir}/%{name}.service
 %else
 # install SYSV init stuff
+%{__mkdir} -p  %{buildroot}%{_initrddir}
 %{__install} -m 0755 init/%{name} %{buildroot}%{_initrddir}/%{name}
 %endif

**Comment by jalbstmeijer** [comment]
el7 rpm werkt prima.

**Comment by maartenq** [comment]
Fix for RHEL 6 init done in a19a15ec611ad5cc64af20875169d7146e67e576

**Comment by maartenq** [comment]
fixed in  0.3.10
