### ISSUE TITLE
NSCAweb stops accepting posts as pcrunner keeps on posting a garbage check result

### ISSUE THREAD

**Issue by jalbstmeijer** [maartenq/pcrunner#94]
in pcrunner.dat I find a bad check result like;

[1534820126] PROCESS_SERVICE_CHECK_RESULT;xxx;eth0 packets;0;eth0 OK  - | awk: cmd. line:4:                                                                         "\nrx_drops: "$4"\ntx_dro� awk: cmd. line:4:                                                                                    ^ unterminated string awk: cmd. line:4:                                                                         "\nrx_drops: "$4"\ntx_dro� awk: cmd. line:4: 

this results in pcrunner not being able to continue posting

Aug 23 11:38:09 xxxx journal: pcrunner.main [22443]: Failed to post 11 results to https://xxxx:5669/queue: HTTP Error 400: Bad Request
Aug 23 11:39:10 xxxx journal: pcrunner.main [22443]: Failed to post 30 results to https://xxxx:5669/queue: HTTP Error 400: Bad Request
Aug 23 11:40:12 xxxx journal: pcrunner.main [22443]: Failed to post 49 results to https://xxxx:5669/queue: HTTP Error 400: Bad Request

Would be nice if pcrunner would detect such bad check result and log it to an error file and not try to post the result.

**Comment by maartenq** [comment]
'Sanitized' performance data'  please the lateste version from devel branch 69d05dd

**Comment by maartenq** [comment]
Fixed in v0.3.11
Performance data 'sanitized'

**Comment by jalbstmeijer** [comment]
> Fixed in v0.3.11
> Performance data 'sanitized'

I will test it.
Could you elaborate on how you tackled this issue?

- Do you mimic the post restrictions of NSCAweb in PCrunner?
- Do you just respond to an NSCAweb http 400 reponse?
- Did you find an other way to validate the check output?

Do you log it when dropping a "faulty" result and do you keep the result to analyse?

While testing, its handy to have the answers as a reference point to know what to expect and not to expect.

**Comment by maartenq** [comment]
1534820126] PROCESS_SERVICE_CHECK_RESULT;xxx;eth0 packets;0;eth0 OK - | awk: cmd. line:4: "\nrx_drops: "$4"\ntx_dro� awk: cmd. line:4: ^ unterminated string awk: cmd. line:4: "\nrx_drops: "$4"\ntx_dro� awk: cmd. line:4: 
maybe not cause
